import os
import uuid
import time
from flask import Flask, request, jsonify, send_from_directory
from flask_socketio import SocketIO, join_room, emit
from flask_compress import Compress
import storage

# ──────────────────────────────────────────────
#  App setup
# ──────────────────────────────────────────────
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_DIR = os.path.join(BASE_DIR, "static")
UPLOAD_DIR = os.path.join(BASE_DIR, "uploads")
os.makedirs(UPLOAD_DIR, exist_ok=True)

ALLOWED_EXTENSIONS = {"png", "jpg", "jpeg", "gif", "webp"}
MAX_IMAGE_BYTES = 10 * 1024 * 1024  # 10 MB

app = Flask(__name__, static_folder=STATIC_DIR, static_url_path="")
app.config["SECRET_KEY"] = os.environ.get("SECRET_KEY", "changeme-secret")
app.config["MAX_CONTENT_LENGTH"] = MAX_IMAGE_BYTES
# Cache static files for 1 year
app.config["SEND_FILE_MAX_AGE_DEFAULT"] = 31536000 

Compress(app)

socketio = SocketIO(
    app,
    cors_allowed_origins="*",
    async_mode="gevent",
    logger=False,
    engineio_logger=False,
)

# Track online users per room: { room: { sid: username } }
online: dict[str, dict] = {}


def _allowed(filename: str) -> bool:
    return "." in filename and filename.rsplit(".", 1)[1].lower() in ALLOWED_EXTENSIONS


# ──────────────────────────────────────────────
#  HTTP Routes
# ──────────────────────────────────────────────

@app.route("/")
def index():
    return send_from_directory(STATIC_DIR, "index.html")


@app.route("/chat")
def chat():
    return send_from_directory(STATIC_DIR, "chat.html")


@app.route("/uploads/<path:filename>")
def serve_upload(filename):
    return send_from_directory(UPLOAD_DIR, filename)


@app.route("/upload", methods=["POST"])
def upload_image():
    """Receive a multipart image, save to disk, return its URL."""
    if "image" not in request.files:
        return jsonify({"error": "No image field"}), 400

    file = request.files["image"]
    if file.filename == "":
        return jsonify({"error": "Empty filename"}), 400

    if not _allowed(file.filename):
        return jsonify({"error": "File type not allowed"}), 400

    ext = file.filename.rsplit(".", 1)[1].lower()
    unique_name = f"{uuid.uuid4().hex}.{ext}"
    save_path = os.path.join(UPLOAD_DIR, unique_name)
    file.save(save_path)

    url = f"/uploads/{unique_name}"
    return jsonify({"url": url}), 200


# ──────────────────────────────────────────────
#  Socket.IO Events
# ──────────────────────────────────────────────

@socketio.on("join")
def on_join(data):
    """Client joins a room. data = {username, room}"""
    username = (data.get("username") or "").strip()
    room = (data.get("room") or "").strip().upper()
    if not username or not room:
        return

    join_room(room)

    # Track online
    if room not in online:
        online[room] = {}
    online[room][request.sid] = username

    # Track user in Supabase
    try:
        storage.upsert_user(username, room, True)
    except Exception as e:
        print(f"Failed to upsert user: {e}")

    # Send message history to this client only
    history = storage.get_messages(room)
    emit("history", history)

    # Notify others that user came online
    emit(
        "user_joined",
        {"username": username, "online_users": list(online[room].values())},
        to=room,
        include_self=False,
    )

    # Send online list to the joining user
    emit("online_users", list(online[room].values()))


@socketio.on("disconnect")
def on_disconnect():
    sid = request.sid
    # Find which room this sid belongs to
    for room, users in list(online.items()):
        if sid in users:
            username = users.pop(sid)
            
            # Update user in Supabase to offline
            try:
                storage.upsert_user(username, room, False)
            except Exception as e:
                print(f"Failed to upsert user: {e}")
                
            emit(
                "user_left",
                {"username": username, "online_users": list(users.values())},
                to=room,
            )
            break


@socketio.on("message")
def on_message(data):
    """
    data = {
        room: str,
        sender: str,
        text: str | None,
        image_url: str | None,
        id: str,       # UUID generated by client
        ts: float,     # Unix timestamp (ms) from client
    }
    """
    room = (data.get("room") or "").strip().upper()
    if not room:
        return

    msg = {
        "id": data.get("id", uuid.uuid4().hex),
        "room": room,
        "sender": data.get("sender", ""),
        "text": data.get("text", ""),
        "image_url": data.get("image_url", ""),
        "ts": data.get("ts", time.time() * 1000),
        "seen": False,
    }

    storage.add_message(room, msg)
    emit("message", msg, to=room)


@socketio.on("typing")
def on_typing(data):
    room = (data.get("room") or "").strip().upper()
    emit("typing", {"username": data.get("username")}, to=room, include_self=False)


@socketio.on("stop_typing")
def on_stop_typing(data):
    room = (data.get("room") or "").strip().upper()
    emit("stop_typing", {"username": data.get("username")}, to=room, include_self=False)


@socketio.on("seen")
def on_seen(data):
    """data = {room, reader, up_to_ts}"""
    room = (data.get("room") or "").strip().upper()
    reader = data.get("reader", "")
    up_to_ts = data.get("up_to_ts", 0)
    storage.mark_seen(room, up_to_ts, reader)
    emit("seen", {"reader": reader, "up_to_ts": up_to_ts}, to=room, include_self=False)


@socketio.on("delete_message")
def on_delete(data):
    """data = {room, msg_id, delete_for: 'me'|'everyone'}"""
    room = (data.get("room") or "").strip().upper()
    msg_id = data.get("msg_id", "")
    delete_for = data.get("delete_for", "me")

    if delete_for == "everyone":
        deleted = storage.delete_message(room, msg_id)
        if deleted:
            emit("delete_message", {"msg_id": msg_id}, to=room)
    else:
        # Just emit back to sender only
        emit("delete_message", {"msg_id": msg_id})


# ──────────────────────────────────────────────
#  Entry point
# ──────────────────────────────────────────────
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    print("╔══════════════════════════════════════╗")
    print(f"║   Private Chat App  •  Port {port:<8} ║")
    print("╚══════════════════════════════════════╝")
    print(f"  Open: http://localhost:{port}")
    print("  Share a room code with a friend!\n")
    # For local development run via python. For production, use Gunicorn with Eventlet.
    socketio.run(app, host="0.0.0.0", port=port, debug=False)
