import os
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "")

if SUPABASE_URL and SUPABASE_KEY:
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
else:
    supabase = None
    print("WARNING: SUPABASE_URL or SUPABASE_KEY is missing. Storage will fail.")

def add_message(room: str, msg: dict) -> dict:
    """Add a message to the Supabase store and return it."""
    if not supabase:
        return msg

    # Supabase uses 'client_id' to store the uuid generated by the frontend,
    # as 'id' is generated by Postgres.
    data = {
        "client_id": msg.get("id"),
        "room": room,
        "sender": msg.get("sender"),
        "text": msg.get("text"),
        "image_url": msg.get("image_url"),
        "ts": msg.get("ts"),
        "seen": msg.get("seen", False)
    }
    
    try:
        supabase.table("messages").insert(data).execute()
    except Exception as e:
        print(f"Error inserting message: {e}")
        
    return msg

def get_messages(room: str) -> list:
    """Return all stored messages for a room."""
    if not supabase:
        return []
        
    try:
        response = supabase.table("messages").select("*").eq("room", room).order("ts").execute()
        msgs = response.data
        
        # Transform back to expected format
        for m in msgs:
            m["id"] = m["client_id"]
        return msgs
    except Exception as e:
        print(f"Error getting messages: {e}")
        return []

def delete_message(room: str, msg_id: str) -> bool:
    """Delete a message by client_id from the Supabase store."""
    if not supabase:
        return False
        
    try:
        res = supabase.table("messages").delete().eq("client_id", msg_id).execute()
        return len(res.data) > 0
    except Exception as e:
        print(f"Error deleting message: {e}")
        return False

def mark_seen(room: str, up_to_ts: float, reader: str) -> None:
    """Mark all messages up to a timestamp as seen by reader."""
    if not supabase:
        return
        
    try:
        # Supabase doesn't easily support "update where ts <= X and sender != reader" in a single simple query via PostgREST client easily without RPC, 
        # but we can fetch them and update, or use in/neq.
        # Let's do it by fetching the IDs that need updating first.
        res = supabase.table("messages").select("id").eq("room", room).lte("ts", up_to_ts).neq("sender", reader).eq("seen", False).execute()
        
        if res.data:
            ids = [row["id"] for row in res.data]
            supabase.table("messages").update({"seen": True}).in_("id", ids).execute()
            
    except Exception as e:
        print(f"Error marking seen: {e}")
