import os
from threading import Lock
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv()

SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "")

if SUPABASE_URL and SUPABASE_KEY:
    supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)
else:
    supabase = None
    print("WARNING: SUPABASE_URL or SUPABASE_KEY is missing. Storage will fail.")

# Thread-safe in-memory cache
# Structure: { "room_code": [list of message dicts] }
_cache = {}
_lock = Lock()


def get_messages(room: str) -> list:
    """Return all stored messages for a room, checking cache first."""
    if not supabase:
        return []
    
    with _lock:
        if room in _cache:
            return _cache[room]
            
    # Cache miss: fetch from Supabase
    try:
        response = supabase.table("messages").select("*").eq("room", room).order("ts").execute()
        msgs = response.data
        
        # Transform back to expected format
        for m in msgs:
            m["id"] = m["client_id"]
            
        with _lock:
            _cache[room] = msgs
            
        return msgs
    except Exception as e:
        print(f"Error getting messages: {e}")
        return []


def add_message(room: str, msg: dict) -> dict:
    """Add a message to the Supabase store and cache it instantly."""
    if not supabase:
        return msg

    # Supabase uses 'client_id' to store the uuid generated by the frontend
    data = {
        "client_id": msg.get("id"),
        "room": room,
        "sender": msg.get("sender"),
        "text": msg.get("text"),
        "image_url": msg.get("image_url"),
        "ts": msg.get("ts"),
        "seen": msg.get("seen", False)
    }
    
    # Instantly update cache
    with _lock:
        if room in _cache:
            _cache[room].append(msg)
    
    # Save to Supabase in background (or synchronously here)
    try:
        supabase.table("messages").insert(data).execute()
    except Exception as e:
        print(f"Error inserting message: {e}")
        
    return msg


def delete_message(room: str, msg_id: str) -> bool:
    """Delete a message by client_id from both cache and Supabase."""
    if not supabase:
        return False
        
    # Update cache
    with _lock:
        if room in _cache:
            _cache[room] = [m for m in _cache[room] if m.get("id") != msg_id]
            
    try:
        res = supabase.table("messages").delete().eq("client_id", msg_id).execute()
        return len(res.data) > 0
    except Exception as e:
        print(f"Error deleting message: {e}")
        return False


def mark_seen(room: str, up_to_ts: float, reader: str) -> None:
    """Mark all messages up to a timestamp as seen by reader in cache and Supabase."""
    if not supabase:
        return
        
    # Update cache
    changed = False
    with _lock:
        if room in _cache:
            for m in _cache[room]:
                if m.get("ts", 0) <= up_to_ts and m.get("sender") != reader and not m.get("seen"):
                    m["seen"] = True
                    changed = True
                    
    # Only update DB if something actually changed
    if changed:
        try:
            res = supabase.table("messages").select("id").eq("room", room).lte("ts", up_to_ts).neq("sender", reader).eq("seen", False).execute()
            if res.data:
                ids = [row["id"] for row in res.data]
                supabase.table("messages").update({"seen": True}).in_("id", ids).execute()
        except Exception as e:
            print(f"Error marking seen: {e}")
